### Create Number Task
POST http://localhost:4000/task/number
Content-Type: application/json

{
    "number": 5
}

###
POST http://localhost:4000/task/message
Content-Type: application/json

{
    "message":"Helloo"
}

### sending email
POST http://localhost:4000/task/email
Content-Type: application/json

{
    "from":"ram@mail.com",
    "to":"ruthwika@mail.com",
    "message":"Hello Ruthwika"
}

### Notification Task
POST http://localhost:4000/task/notification
Content-Type: application/json

{
    "title":"vc",
    "message":"fgxd"
}

###
GET http://localhost:4000/task/all 